### ISSUE TITLE
Bør ta hensyn til ulike versjoner av Noark 5, eller dokumentere aktuelle versjoner

### ISSUE THREAD

**Issue by joergen-vs** [IKAMR/digitalt-depot-prosesser#1]
Vær klar over at de ulike versjonene av Noark 5 har litt ulik struktur og navn på elementene.
I xml-queries_noark5_2020-10-19.txt finnes det f.eks. referanser til sakspart. Denne er omdøpt i nyeste versjon av Noark, til part (https://github.com/arkivverket/schemas/blob/c4d3fbfdce36f1284d47caad644ef533afdbed63/N5/latest/arkivstruktur.xsd#L233)

**Comment by solfeggietto** [comment]
Takk for innspill, vi skal lage målrettede spørringer for Noark 5 v3.1, v4.0 og v5.0 på ulikhetene.

Her har vi dokumentert alle endringer i Noark 5 xsd-skjemaer fra v3.1 til v4.0 til v5.0 som vi da vil implementere målrettet:
https://github.com/IKAMR/digitalt-depot-prosesser/blob/master/depot/Noark5_diff_v3.1_v4.0_v5.0_2020-11-01.pdf

Samt også tillegg for virksomhetsspesifikke metadata:
https://github.com/IKAMR/digitalt-depot-prosesser/blob/master/depot/Noark5_virksomhetsspesifikkeMetadata_v3.1_4.0_5.0.pdf
